### ISSUE TITLE
I cannot find the "mangarock.db" file in the directory

### ISSUE THREAD

**Issue by mfernd** [waicool20/mr2tachiyomi#11] opened 2019-12-05 00:22 UTC
Hello,
I want to copy the `mangarock.db` file from the `com.mangarock.mangarock.mangarock.mangarock.android.lotus/` directory, but I don't see any file or folder that resembles it.
Do you have any ideas?

A screenshot of my folder :
![image](https://user-images.githubusercontent.com/22498591/70192878-84df8700-16fd-11ea-8724-e08f286bf40b.png)

**Comment by waicool20** [comment] 2019-12-05 02:10
Duplicate of #6, please refer to my reply over there.

 https://github.com/waicool20/mr2tachiyomi/issues/6

**Closed as completed by waicool20** 2019-12-05 02:10 UTC
